### ISSUE TITLE
[Home] Show product lists by thumbnails

### ISSUE THREAD

**Issue by hahuutin** [hahuutin/shop-management#9]
**Todos**:

- [x] Using axios fetch data and show data into UI thumbnail
- [ ] Icon [loading](http://blueprintjs.com/docs/#core/components/progress/spinner) shown while wait fetching data done
- [ ] Show error message in [callouts](http://blueprintjs.com/docs/#core/components/callout) if fetching data failed.

**Mock API:** https://59bb9db81707760011379d8c.mockapi.io/products
**Suggestion:**
+ Axios for HTTP request
+ Blueprintjs for UI product thumnail
+ FlexboxGrid for Layout
+ Styled-Components for some customize styles
